### ISSUE TITLE
Give an example of what is meant by a robust macro and how things go wrong

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/reflect#1]
The example I like to use is taking a single struct field and wrapping it in a new struct. This is a real life use case drawn from how `serde_derive` handles `serialize_with` attributes. Conceptually:

```rust
let input: syn::DeriveInput = syn::parse(...).unwrap();

// Pull out one of the field types.
let type_of_field_x: syn::Type = /* ... */;

quote! {
    // Not robust.
    struct Wrapper<'a> {
        x: &'a #type_of_field_x,
    }

    Wrapper { x: &self.x }
}
```

Making the `quote!` part of this simply generate compilable code for all possible values of `type_of_field_x` is extremely involved. The macro author needs to consider and handle all of the following in order to make this work:

- Lifetime parameters used by `type_of_field_x`,
- Type parameters used by `type_of_field_x`,
- Associated types used by `type_of_field_x`,
- Where-clauses on `input` that constrain any of the above,
- Similarly, trait bounds on type parameters of `input`,
- Where-clauses or bounds affecting any *other* fields of `input`,
- Type parameter defaults on `input` that need to be stripped.

In contrast, the `reflect` library will be able to get it right every single time with much less thought from the macro author. Possibly as trivial as:

```rust
let wrapper: reflect::Type = reflect::new_struct_type();

wrapper.instantiate(vec![input.get_field("x").reference()])
```

**Comment by dtolnay** [comment]
My explanation in filing this issue turned out good enough. :laughing: Added to the readme in 3c98f65496db688870f31018babc7c24b5a6b5bb.

**Comment by teohhanhui** [comment]
I hope I have understood correctly that `reflect::new_struct_type` is within the scope of this project, but just not implemented yet?
